name: esbuild Compilation & npm Publish Workflow

on:
  workflow_call:
    inputs:
      branch:
        description: 'Set the branch to use for automation tests'
        type: string
        required: false
        default: 'main'
      nodeVersion:
        description: version of node to use. It's better to specify latest, lts/* or lts/-1 than to hardode numbers
        type: string
        default: lts/*
        required: false
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to use for automation tests'
        type: string
        required: false
        default: 'main'
      nodeVersion:
        description: version of node to use. It's better to specify latest, lts/* or lts/-1 than to hardode numbers
        type: string
        default: lts/*
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - name: bundle for web
        run: yarn bundle:web
      - name: Update for Bundling
        run: node scripts/updateForBundling.js
      - name: Generate Bundle
        run: |
          yarn build
          node scripts/build.js
      - name: Post Bundling Update
        run: node scripts/postBundlingUpdate.js
      - name: Publish a Package
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
